### PR TITLE
Fix transactionDetailsModal's TokenAmountsBox amounts

### LINKED ISSUE #1429: Amount details on DW are wrong
On DW, displayed amounts in the TX details modal are wrong for some TXs. Probably the case on MW too.
The culprit seems to be in `getTransactionAssetAmounts` that was recently updated.

### PR DESCRIPTION
**Pull request by mvaivre**
Fixes #1429

### CODE REVIEW

File: apps/desktop-wallet/src/components/TokenAmountsBox.tsx [hunk 1]
```diff
@@ -24,45 +24,62 @@ import { useAppDispatch } from '@/hooks/redux'
...
+  let alphForDust = BigInt(0)
+
+  if (shouldAddAlphForDust) {
+    const userSpecifiedAlphAmount = assetAmounts.find((asset) => asset.id === ALPH.id)?.amount
+    const { attoAlphAmount, tokens, extraAlphForDust } = getTransactionAssetAmounts(assetAmounts)
+    const alphAsset = { id: ALPH.id, amount: attoAlphAmount }
+
+    alphForDust = extraAlphForDust
+    amounts = userSpecifiedAlphAmount ? [alphAsset, ...tokens] : [...tokens, alphAsset]
+  }
```
Comment (nop33) [inline apps/desktop-wallet/src/components/TokenAmountsBox.tsx:57]: Let's put all that into a `useMemo` call, it feels wrong running all this logic on every re-render.

File: apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/FTAmounts.tsx [hunk 2]
```diff
@@ -11,7 +11,9 @@ const FTAmounts = ({ tx, refAddressHash }: TransactionDetailsModalTxProps) => {
 
   const isMoved = infoType === 'move'
 
-  return <CheckAmountsBox assetAmounts={fungibleTokens} highlight={!isMoved} showPlusMinus={!isMoved} />
+  const assetAmounts = fungibleTokens.map(({ id, amount }) => ({ id, amount }))
```
Comment (nop33) [inline apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/FTAmounts.tsx:14]: Is this rly necessary? Typescript shouldn't really complain since the props are already there.

File: apps/desktop-wallet/src/components/TokenAmountsBox.tsx (hunk 1 above)
Comment (mvaivre) [reply apps/desktop-wallet/src/components/TokenAmountsBox.tsx]: Done

File: apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/FTAmounts.tsx (hunk 2 above)
Comment (mvaivre) [reply apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/FTAmounts.tsx]: Removed
