### PR TITLE
Fix mobile wallet address discovery

### LINKED ISSUE #1458: Address discovery in mw in groupless branch is broken

### PR DESCRIPTION
**Pull request by nop33**
- Closes #1458

### CODE REVIEW

File: apps/mobile-wallet/src/store/addressDiscoverySlice.ts [hunk 1]
```diff
@@ -71,6 +71,7 @@ export const discoverAddresses = createAsyncThunk(
         const maxIndexBeforeFirstGap = findMaxIndexBeforeFirstGap(indexesOfGrouplessAddresses)
         const index = findNextAvailableAddressIndex(maxIndexBeforeFirstGap, checkedGrouplessIndexes)
         checkedGrouplessIndexes.push(index)
+        checkedGrouplessIndexes.sort((a, b) => a - b)
```
Comment (mvaivre) [inline apps/mobile-wallet/src/store/addressDiscoverySlice.ts:74]: Nit: we could extract the sort function: 
```ts
const ascOrder = (a: number, b: number) => a - b
```

**Review by mvaivre — APPROVED** [review]
LGTM! One nit suggestion.
