### PR TITLE
Add WC QR code scan btn in pairings modal & bug fixes

### LINKED ISSUE #277: Tapping the WalletConnect button should give access to QR code scanning

### PR DESCRIPTION
**Pull request by nop33**
Closes #277

### CODE REVIEW

File: apps/mobile-wallet/src/components/layout/ScrollScreen.tsx [hunk 1]
```diff
@@ -88,7 +88,7 @@ const ScrollScreen = ({
         alwaysBounceVertical={true}
         onScroll={screenScrollHandler}
         onScrollEndDrag={scrollEndHandler}
-        style={{ overflow: SCREEN_OVERFLOW, paddingTop: headerOptions ? 15 : 0 }}
+        style={{ overflow: SCREEN_OVERFLOW }}
```
Comment (nop33) [inline apps/mobile-wallet/src/components/layout/ScrollScreen.tsx:91]: @mvaivre this fixes the bottom padding issues on Android. I couldn't find any side-effects of this change. Maybe you remember better why we had this? I checked both iOS and Android

Comment (mvaivre) [reply apps/mobile-wallet/src/components/layout/ScrollScreen.tsx:91]: Nope I can't remember. I don't find any issues on iOS either sooo 🤷

**Review by mvaivre — APPROVED** [review]
Code looks good to me and testing looked good as well! 👏
