### PR TITLE
Secrets fixes

### LINKED ISSUE #543: Cannot copy private key after upgrading to 2.3.0
> Error: Invalid version: got undefined, expected: 1

### PR DESCRIPTION
**Pull request by nop33**
These changes were already included in the mobile secrets PRs, so I cherry-picked them to fix #543 

Closes #543

### CODE REVIEW

**Comment by nop33** [comment]
Pushed one more fix, sorry

File: apps/desktop-wallet/src/modals/SettingsModal/WalletsSettingsSection.tsx [hunk 1]
```diff
@@ -108,15 +109,40 @@ const WalletsSettingsSection = () => {
...
               {t('Lock current wallet')}
             </Button>
-            <Button role="secondary" onClick={() => setIsQRCodeModalVisible(true)}>
-              {t('Export current wallet')}
-            </Button>
+
+            <ButtonTooltipWrapper
+              data-tooltip-id="default"
+              data-tooltip-content={
+                activeWallet.isPassphraseUsed ? t('To export this wallet use it without a passphrase') : ''
```
Comment (nop33) [inline apps/desktop-wallet/src/modals/SettingsModal/WalletsSettingsSection.tsx:116]: To avoid confusion, passphrase wallets should not be exportable, since we are not exporting the passphrase. The user ends up with a different wallet on their mobile (the one with the 24 words)

File: apps/desktop-wallet/src/modals/SettingsModal/WalletsSettingsSection.tsx [hunk 2]
```diff
@@ -108,15 +109,40 @@ const WalletsSettingsSection = () => {
...
               {t('Show your secret recovery phrase')}
             </Button>
-            <Button variant="alert" onClick={() => setWalletToRemove(activeWallet as ActiveWallet)}>
-              {t('Remove current wallet')}
-            </Button>
+
+            <ButtonTooltipWrapper
+              data-tooltip-id="default"
+              data-tooltip-content={
+                activeWallet.isPassphraseUsed ? t('To delete this wallet use it without a passphrase') : ''
```
Comment (nop33) [inline apps/desktop-wallet/src/modals/SettingsModal/WalletsSettingsSection.tsx:135]: I think it makes sense to disable deleting the wallet when it's unlocked with a passphrase. USers might think that they are deleting the "passphrase-enabled" wallet, where in fact they are deleting the 24-words wallet. We don't store any "passphrase-enabled" wallet, so there's nothing to delete.

Comment (mvaivre) [reply apps/desktop-wallet/src/modals/SettingsModal/WalletsSettingsSection.tsx:135]: Very valid point!

File: apps/desktop-wallet/src/modals/SettingsModal/WalletsSettingsSection.tsx (hunk 1 above)
Comment (mvaivre) [reply apps/desktop-wallet/src/modals/SettingsModal/WalletsSettingsSection.tsx:116]: 💯

**Review by mvaivre — APPROVED** [review]
LGTM!
