### PR TITLE
Fix AssetBadge decimals

### LINKED ISSUE #230: [DW] Wrong decimal display for token-list assets (in AssetBadge)
The assets' value seems to be wrongly displayed for assets with `decimals` equal to 0.

### PR DESCRIPTION
**Pull request by mvaivre**
Fixes #230

### CODE REVIEW

File: apps/desktop-wallet/src/components/AssetBadge.tsx [hunk 1]
```diff
@@ -53,7 +53,7 @@ const AssetBadge = ({ assetId, amount, simple, className }: AssetBadgeProps) =>
       {nftInfo?.name ? (
         <AssetSymbol>{nftInfo?.name}</AssetSymbol>
       ) : amount !== undefined ? (
-        <Amount value={amount} suffix={assetInfo?.symbol} />
+        <Amount value={amount} suffix={assetInfo?.symbol} decimals={assetInfo?.decimals} />
```
Comment (polarker) [inline apps/desktop-wallet/src/components/AssetBadge.tsx:56]: Optional parameters backfire quite often. Could use explicit parameters for important ones, in this case, we could introduce `<AssetAmount mandatoryDecimals=.../>`

**Review by polarker — APPROVED** [review]
The fix LGTM 👍 Just a remark on coding practice

File: apps/desktop-wallet/src/components/AssetBadge.tsx (hunk 1 above)
Comment (mvaivre) [reply apps/desktop-wallet/src/components/AssetBadge.tsx:56]: Agreed. The `Amount` component is due for a cleanup. I think we can do better with clever types. Just an idea :
- Expecting a mandatory amount type prop to be either `fiat` or `asset`
- If it's asset, then the `decimals` field is mandatory.

**Review by nop33 — APPROVED** [review]
