### PR TITLE
Expo 50 again

### LINKED ISSUE #191: Update to Expo 50 when it goes out of beta
Amazing news!

https://expo.dev/changelog/2023/12-12-sdk-50-beta

> `npx expo prebuild` no longer executes `[npm|yarn|pnpm|bun] install` on each run by default. If no changes are made to the dependencies in the package.json (default when using the standard template) then the Node module installation step will be skipped. The only changes outside of the native directories will likely only be the package.json scripts now.

This will probably solve this problem of ours: https://github.com/alephium/alephium-frontend/issues/154

Other cool stuff:

> Expo Dev Tools Plugin API. [First discussed in August 2023](https://expo.dev/changelog/2023/08-10-dev-tools-plugins), this API provides a foundation for library authors (and adventurous app developers) to build browser-based plugins to debug and interact with aspects of their library / app. To validate and demonstrate the API, we also built a few plugins for popular tools: Apollo Client, TanStack Query, TinyBase, and React Navigation — and you can find them in the [expo/dev-plugins repository](https://github.com/expo/dev-plugins).

> `expo-secure-store` gets a handful of new improvements. By popular demand, we’ve introduced synchronous getItem and setItem functions! We’ve also unified the behavior as much as possible across Android and iOS — other than different types of exceptions resulting from different native implementations, all of the functions now behave the same. This introduces a small breaking change — when fetching a value which doesn’t exist in a keychain expo-secure-store will now always return null. Previously, Android would throw an exception and iOS would return null. [Learn more about other changes in the changelog](https://github.com/expo/expo/blob/main/CHANGELOG.md).

> `tsconfigPaths` is now enabled in `@expo/metro-config` by default: this means that all you need to do to add path aliases is configure the paths property in your tsconfig.json. For example, `"@/*": ["src/*"]` will allow you to write code like import Button from `'@/components/Button';` anywhere in your codebase and have it resolve to the correct location within src. [Learn more](https://docs.expo.dev/guides/typescript/#path-aliases).

---

It should go out of beta in about 1 month.

### PR DESCRIPTION
**Pull request by mvaivre**
Fixes #191

### CODE REVIEW

File: apps/mobile-wallet/src/screens/new-wallet/AddBiometricsScreen.tsx [hunk 1]
```diff
@@ -107,6 +107,7 @@ const AnimationContainer = styled.View`
 
 const StyledAnimation = styled(LottieView)`
   width: 300px;
+  height: 120%;
```
Comment (nop33) [inline apps/mobile-wallet/src/screens/new-wallet/AddBiometricsScreen.tsx:110]: nit: It's very strange to see a value larger than `100%`! Is this the right way to fix the issue?

**Review by nop33 — COMMENTED** [review]
1. Can you please port the apps/mobile-wallet/metro.config.js change from this commit? 🙏 https://github.com/alephium/alephium-frontend/commit/40e141532d162f607f4947b71d0764db5e265eed (originally requested in https://github.com/alephium/alephium-frontend/pull/358#pullrequestreview-1887679138)
1. When I do pod-install I get a diff. Do you also get this? (see below for diff)
1. I am hesitant merging this on `master`. Maybe it should go into a new `develop` or `next` branch so that we have more control over what goes on master (like when we need to fix urgent production bugs)
1. Was every part of the code that uses a package from the [breaking changes list](https://github.com/alephium/alephium-frontend/pull/358#discussion_r1494087597) got tested?

<details><summary>See diff</summary>

```diff
diff --git a/apps/mobile-wallet/ios/Alephium.xcodeproj/project.pbxproj b/apps/mobile-wallet/ios/Alephium.xcodeproj/project.pbxproj
index 7f1e38ca4..6a662ef37 100644
--- a/apps/mobile-wallet/ios/Alephium.xcodeproj/project.pbxproj
+++ b/apps/mobile-wallet/ios/Alephium.xcodeproj/project.pbxproj
@@ -170,8 +170,8 @@
 				LastUpgradeCheck = 1130;
 				TargetAttributes = {
 					13B07F861A680F5B00A75B9A = {
+						DevelopmentTeam = Z3J8P4JW24;
 						LastSwiftMigration = 1250;
-						DevelopmentTeam = "Z3J8P4JW24";
 						ProvisioningStyle = Automatic;
 					};
 				};
@@ -330,7 +330,10 @@
 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
 				CLANG_ENABLE_MODULES = YES;
 				CODE_SIGN_ENTITLEMENTS = Alephium/Alephium.entitlements;
+				CODE_SIGN_IDENTITY = "Apple Development";
+				CODE_SIGN_STYLE = Automatic;
 				CURRENT_PROJECT_VERSION = 1;
+				DEVELOPMENT_TEAM = Z3J8P4JW24;
 				ENABLE_BITCODE = NO;
 				GCC_PREPROCESSOR_DEFINITIONS = (
 					"$(inherited)",
@@ -353,9 +356,6 @@
 				SWIFT_VERSION = 5.0;
 				TARGETED_DEVICE_FAMILY = "1,2";
 				VERSIONING_SYSTEM = "apple-generic";
-				DEVELOPMENT_TEAM = "Z3J8P4JW24";
-				CODE_SIGN_IDENTITY = "Apple Development";
-				CODE_SIGN_STYLE = Automatic;
 			};
 			name = Debug;
 		};
@@ -366,7 +366,10 @@
 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
 				CLANG_ENABLE_MODULES = YES;
 				CODE_SIGN_ENTITLEMENTS = Alephium/Alephium.entitlements;
+				CODE_SIGN_IDENTITY = "Apple Development";
+				CODE_SIGN_STYLE = Automatic;
 				CURRENT_PROJECT_VERSION = 1;
+				DEVELOPMENT_TEAM = Z3J8P4JW24;
 				INFOPLIST_FILE = Alephium/Info.plist;
 				IPHONEOS_DEPLOYMENT_TARGET = 13.4;
 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
@@ -383,9 +386,6 @@
 				SWIFT_VERSION = 5.0;
 				TARGETED_DEVICE_FAMILY = "1,2";
 				VERSIONING_SYSTEM = "apple-generic";
-				DEVELOPMENT_TEAM = "Z3J8P4JW24";
-				CODE_SIGN_IDENTITY = "Apple Development";
-				CODE_SIGN_STYLE = Automatic;
 			};
 			name = Release;
 		};
@@ -444,11 +444,7 @@
 				ONLY_ACTIVE_ARCH = YES;
 				OTHER_CFLAGS = "$(inherited)";
 				OTHER_CPLUSPLUSFLAGS = "$(inherited)";
-				OTHER_LDFLAGS = (
-					"$(inherited)",
-					"-Wl",
-					"-ld_classic",
-				);
+				OTHER_LDFLAGS = "$(inherited)";
 				REACT_NATIVE_PATH = "${PODS_ROOT}/../../../../node_modules/react-native";
 				SDKROOT = iphoneos;
 				USE_HERMES = true;
@@ -502,11 +498,7 @@
 				MTL_ENABLE_DEBUG_INFO = NO;
 				OTHER_CFLAGS = "$(inherited)";
 				OTHER_CPLUSPLUSFLAGS = "$(inherited)";
-				OTHER_LDFLAGS = (
-					"$(inherited)",
-					"-Wl",
-					"-ld_classic",
-				);
+				OTHER_LDFLAGS = "$(inherited)";
 				REACT_NATIVE_PATH = "${PODS_ROOT}/../../../../node_modules/react-native";
 				SDKROOT = iphoneos;
 				USE_HERMES = true;
diff --git a/apps/mobile-wallet/ios/Podfile.lock b/apps/mobile-wallet/ios/Podfile.lock
index 53e183213..827118315 100644
--- a/apps/mobile-wallet/ios/Podfile.lock
+++ b/apps/mobile-wallet/ios/Podfile.lock
@@ -1684,4 +1684,4 @@ SPEC CHECKSUMS:
 
 PODFILE CHECKSUM: 595f099defc45d3f3fbd6e5ddddf7dec7626b524
 
-COCOAPODS: 1.14.3
+COCOAPODS: 1.15.2
```

</details>

**Comment by nop33** [comment]
Changed target branch to `next`

**Comment by nop33** [comment]
I would like to prioritize merging this PR so that we can exclude the case of dependency hell.

**Review by nop33 — APPROVED** [review]
I'll approve and merge it so that we can move on. Let's figure out the pod-install issues together later, maybe on a call.
